-- Migration: Convert workout library_workout_id from text format to NanoID format
-- This migration updates all library_workout_id references in plan_data JSONB columns
-- Tables affected: training_plans, plan_instances

-- Create a temporary mapping table
CREATE TEMP TABLE workout_id_mapping (
  old_id TEXT PRIMARY KEY,
  new_id TEXT NOT NULL
);

-- Insert all mappings (222 workouts)
-- Generated by scripts/migrate_workout_ids.py
INSERT INTO workout_id_mapping (old_id, new_id) VALUES
  ('cardio_drift_test', 'RVrReapuzt'),
  ('base_fitness_60_65_threshold', 'R8KYR4Whpn'),
  ('1hr_base_fitness_60_65_threshold', '_mGszlLEZM'),
  ('3x12_tempo', '84_BwfWWG3'),
  ('3x15_tempo', 'mCWHihFeHJ'),
  ('active_recovery', 'g9hgxpDgQA'),
  ('base_fitness_60_65_threshold_2', '2b5XhWqy5E'),
  ('35hr_base_fitness', 'l-4yEPG2_3'),
  ('zwift_new_workout_in_watopia', 'EolswA2guC'),
  ('15hr_base_fitness', '0DWLI0Q_yd'),
  ('ftp_progression_2_5x7', 'k7BoAmaWBS'),
  ('ftp_over_unders_3_sets_8x1', 'WQWmiYxbRa'),
  ('general_endurance', '0CkcUoLbfm'),
  ('zone_2_with_cadence_variation', 'l9LwRr931J'),
  ('4hr_base_fitness', 'GoneJ-oasb'),
  ('tempo_repeats', 'bSHgQLUvBB'),
  ('tempo_repeats_2', 'Hi_eprkbQG'),
  ('the_benchmark_test', 'aIu67pB0ch'),
  ('5min_strength_efforts_zone_3', 'C2kCY0ykdB'),
  ('base_fitness_training_zone_two', 'SLArVTlccR'),
  ('sweet_spot_repeats', 'P8Q6UWW3PP'),
  ('base_fitness_training_zone_two_2', 'I7CZ-hAlYs'),
  ('4020s_5min', 'uaL8NdRe3t'),
  ('vo2_repeats_5x3', '-KBNGa6SKK'),
  ('5min_strength_efforts_zone_3_2', 'mEZYwd_0bD'),
  ('5min_strength_efforts', 'XRfjAlFvYa'),
  ('15hr_base_fitness_60_65_threshold', 'hSfFEj6U4Y'),
  ('threshold', 'PmhHH8qONT'),
  ('10min_strength_efforts', 'YP4oEdSUi7'),
  ('threshold_2', 'Q-RX85KwbZ'),
  ('base_fitness_training_zone_two_3', 'jbr1FrF0Oq'),
  ('2x20_tempo', 'viofn6PdMi'),
  ('tempo_with_spikes', 'IIr3dQHEVi'),
  ('3030s_3x10', 'hNgEwVnI6e'),
  ('tempo_with_spikes_2', '78wtp8KIIS'),
  ('4020s_5min_2', '76m8P3pLYf'),
  ('12060s', 'rzTJX48jZ-'),
  ('activations', '_o9B8OJGfz'),
  ('threshold_test_5_20', '5U9N-nwo0A'),
  ('the_benchmark_test_2', 'BNL1DITb1-'),
  ('tempo_with_spikes_3', '1mBgIPQOb4'),
  ('sub_threshold_efforts', '_gat8S0JsS'),
  ('sub_threshold_low_cadence_efforts', 'mye7_ROPtk'),
  ('optional_aerobic_endurance_bike', 'lifTwRGUFJ'),
  ('fitness_test_ftp_and_threshold_hr_50_mins', 'xXNTddsxnh'),
  ('map_efforts', '1qNVeYOPMI'),
  ('sub_threshold_efforts_2', 'v2jkfJi2Qe'),
  ('sub_threshold_efforts_3', 'OW0xbY-fUU'),
  ('sub_threshold_efforts_4', 't1gigdPFaw'),
  ('map_efforts_2', 'zFHWyi1Twc'),
  ('above_and_below_threshold', 'zBksgZZktK'),
  ('sub_threshold_efforts_5', 'c5_zHP0mAb'),
  ('sub_threshold_efforts_6', 'DE_f93Hhlw'),
  ('optional_aerobic_endurance_ride', '3QT_71jZer'),
  ('optional_aerobic_endurance_bike_2', 'ZCcjOIQww7'),
  ('optional_aerobic_endurance_ride_2', '5vOlRUA6OW'),
  ('optional_aerobic_endurance_bike_3', '4UkPEDucCO'),
  ('optional_aerobic_endurance_bike_4', 'v-XP9Jl4SE'),
  ('above_and_below_threshold_2', 'VcYa899-u-'),
  ('above_and_below_threshold_3', 'LSsyY0WzV4'),
  ('threshold_efforts', '4a1oWEjTnN'),
  ('optional_aerobic_endurance_bike_5', 'Z0609zekdg'),
  ('threshold_efforts_2', 'TnzTTWprtj'),
  ('threshold_efforts_3', 'iTRBzYIbes'),
  ('threshold_efforts_4', 'kC2kEfzvxG'),
  ('map_efforts_3', 'eb9kpzzCHM'),
  ('map_efforts_4', 'oysT-GpiZp'),
  ('map_efforts_5', 'ZFPpGsxdDs'),
  ('map_efforts_6', 'xE9N92jekF'),
  ('threshold_efforts_5', '8Y43CqM4RI'),
  ('sub_threshold_effort', '8SMU9vpjQi'),
  ('map_efforts_7', 'D-BRjWrU8c'),
  ('threshold_efforts_6', 'AEWEYPM2sx'),
  ('sub_threshold_efforts_7', 'h6XLqTB7j2'),
  ('sub_threshold_efforts_8', 'xpWuIJOjF9'),
  ('sub_threshold_efforts_9', 'q5TkovQ-VS'),
  ('sub_threshold_efforts_10', 'T6_QU7ORNP'),
  ('sub_threshold_efforts_11', 'JSvG1H-zPu'),
  ('sub_threshold_efforts_12', '4N0mlarajz'),
  ('sub_threshold_efforts_13', 'ljppiG3HDE'),
  ('optional_aerobic_endurance_ride_3', 'v-RKuuTqsU'),
  ('above_and_below_threshold_4', 'JVq3m2pUpS'),
  ('above_and_below_threshold_5', 'p_xKMTk5Me'),
  ('threshold_efforts_7', 'qFccQLPCge'),
  ('threshold_efforts_8', 'rxniUsbsBD'),
  ('threshold_efforts_9', '151FCujAQP'),
  ('map_efforts_8', 'c_-JsDwWVD'),
  ('sub_threshold_efforts_14', 'h9lRssHIpv'),
  ('sub_threshold_effort_2', 'k7kNYEp-OB'),
  ('optional_aerobic_endurance_ride_4', 'XPmytXufAH'),
  ('optional_aerobic_endurance_ride_5', 'bMxaHDZVPr'),
  ('optional_aerobic_endurance_ride_6', 'o_bQnr021Z'),
  ('threshold_efforts_10', '-31nppg9xi'),
  ('30_s_x_4m_interval_repeats', 'dwJlJsPTi8'),
  ('3x15min_sweet_spot', 'JwuRQfdjQH'),
  ('70min_base_ride', 'G1Hcl_Hmes'),
  ('27hr_endurance_ride', 'MauBD8KIAt'),
  ('2x20min_sweet_spot', 'TKjNnGfqja'),
  ('5x4min_vo2_max_intervals', 'ttJMHzuALe'),
  ('28hr_endurance_ride', 'fCKMQ4IGQv'),
  ('2x20min_sweet_spot_2', 'ZtTJAIr5fh'),
  ('3x12min_vo2_max_intervals', '51Cf-s4oHk'),
  ('30hr_endurance_ride', '_lwXLy2CIO'),
  ('50min_sweet_spot', '12v--VJYcj'),
  ('60min_base_ride', 'JzC7WRg6YR'),
  ('30min_tempo', '9TqktQUP34'),
  ('22hr_endurance_ride', 'Q8oMlf6Ov2'),
  ('70min_base_ride_2', 'Fw14oioPjY'),
  ('70min_base_ride_3', 'JdxtqVB58t'),
  ('2x10min_sweet_spot', 'QWGhP_a4PM'),
  ('70min_base_ride_4', 'RbCExvBKcm'),
  ('22hr_endurance_ride_2', 'ppZH8Q1OWi'),
  ('60min_base_ride_2', '1ANYcdRzo3'),
  ('75min_base_ride', 'AdFcUOlQIn'),
  ('2x12min_sweet_spot', 'FahmCCGARN'),
  ('75min_base_ride_2', '49w0Pqw3e9'),
  ('24hr_endurance_ride', '1TRkExfH-p'),
  ('65min_base_ride', '-hxlD8iVrl'),
  ('80min_base_ride', 'rEn9g0XGZN'),
  ('2x14min_sweet_spot', 'IyoVnU0dTF'),
  ('80min_base_ride_2', '0c7gKPxUez'),
  ('26hr_endurance_ride', 'zcYTeQzhW0'),
  ('70min_base_ride_5', 'dOb8twpaQ1'),
  ('23hr_endurance_ride', 'lC-cwFzoT9'),
  ('55min_base_ride', 'Afv1YZSGng'),
  ('24hr_endurance_ride_2', 'wP0SXhiv7j'),
  ('15hr_endurance_ride', 'B3vBYe4DQ4'),
  ('15min_sweet_spot', 'NA0U-R9u6G'),
  ('60min_base_ride_3', 'axicdQmx31'),
  ('26hr_endurance_ride_2', 'YGtVUpy-Sp'),
  ('20min_sweet_spot', 'cDxPYMDUXC'),
  ('3x12min_sweet_spot', 'Scaq2jrAV_'),
  ('65min_base_ride_2', '3xoINn_BmC'),
  ('28hr_endurance_ride_2', 'OV3dF7TB3H'),
  ('25min_sweet_spot', 'brWPDQ24ph'),
  ('19hr_endurance_ride', 'I4emNgqFpL'),
  ('80min_base_ride_3', 'w18uZW53Ud'),
  ('3x15min_sweet_spot_2', 'xXzRipOpOG'),
  ('30min_sweet_spot', '5ygi79mY8Z'),
  ('3x10min_vo2_max_intervals', 'Aj90EQ0EpV'),
  ('40min_sweet_spot', 'q9TcvH9JTw'),
  ('5x4min_vo2_max_intervals_2', 'TBtNuC1MN4'),
  ('31hr_endurance_ride', 'x64BuWn6dW'),
  ('2x15min_sweet_spot', 'yJ3V_Dd0Db'),
  ('21hr_endurance_ride', 'SbU-RClSxQ'),
  ('85min_base_ride', 'N2ljjSL-iX'),
  ('4x5min_vo2_max_intervals', 'NlXtlfqBqZ'),
  ('32hr_endurance_ride', '6MXSuUkilV'),
  ('3x12min_vo2_max_intervals_2', 'AV7Aa9Zhma'),
  ('3x12min_vo2_max_intervals_3', '7LaE3WQWO2'),
  ('32hr_endurance_ride_2', 'GH8jpWT8o9'),
  ('2x18min_sweet_spot', 'iVmxBrk7vc'),
  ('5x5min_vo2_max_intervals', 'F2HBwuGzgC'),
  ('33hr_endurance_ride', 'eC3hvOvUJV'),
  ('3x15min_vo2_max_intervals', '5VGVMXXQbi'),
  ('2x3min_vo2_max_intervals', 'o4GdfPEvs9'),
  ('50min_base_ride', 'OAZnpRKfb_'),
  ('3x3min_vo2_max_intervals', 'Hg9uzVFVFP'),
  ('45min_base_ride', '_hElRLTndu'),
  ('25hr_endurance_ride', 'mJJoWHpcL-'),
  ('17hr_endurance_ride', 'a65rm3QG6-'),
  ('2x10min_sweet_spot_2', 'YKjfFOH6UM'),
  ('2x12min_sweet_spot_2', 'G_3ifex6d_'),
  ('30min_sweet_spot_2', 'Ko4lpG3Oth'),
  ('2x4min_vo2_max_intervals', '7s7PmKD-c2'),
  ('55min_base_ride_2', 'YJsHkDCcyo'),
  ('30min_sweet_spot_3', 'cxebNWVuzS'),
  ('10min_sweet_spot', 'FNILGQnzeb'),
  ('2x15min_sweet_spot_2', '3dk8Sosttz'),
  ('2x3min_vo2_max_intervals_2', 'yFC4ceqiFs'),
  ('90min_mixed_workout', 'vV7d7WNO7G'),
  ('20min_sweet_spot_2', 'XJdrfJNcxJ'),
  ('60min_mixed_workout', '2IdsUqrXvn'),
  ('60min_mixed_workout_2', 'VeNjnYWgC8'),
  ('30hr_endurance_ride_2', 'yJRlCacYBe'),
  ('2x12min_sweet_spot_3', 'Eujm5sHvjX'),
  ('60min_mixed_workout_3', 'jtbjkwIqMy'),
  ('33hr_endurance_ride_2', 'Yt79xavlDf'),
  ('2x20min_sweet_spot_3', '2EIJqVqLfQ'),
  ('37hr_endurance_ride', 'vHxcCrMQmP'),
  ('2x5min_vo2_max_intervals', 'mHtmTjI_oD'),
  ('20hr_endurance_ride', 'sQRev-Jq05'),
  ('60min_mixed_workout_4', 'vRqiBaIJzA'),
  ('30hr_endurance_ride_3', 'iSO7DdQzhV'),
  ('2x15min_vo2_max_intervals', 'rM2dmuInx6'),
  ('35hr_endurance_ride', 'WgaRMvxe5E'),
  ('2x10min_vo2_max_intervals', 'Qy10luOAeX'),
  ('40hr_endurance_ride', 'P01a0jICv4'),
  ('2x4min_vo2_max_intervals_2', '7y4eAHEkVn'),
  ('25hr_endurance_ride_2', 'TAj8_3cLLW'),
  ('30hr_endurance_ride_4', 'GW0hX4mAiD'),
  ('60min_base_ride_4', 'JRyco9f50v'),
  ('35hr_endurance_ride_2', 'VFJEbQUCVl'),
  ('55min_base_ride_3', '0WqrSa0TDn'),
  ('20hr_endurance_ride_2', 'vpXiLcofYH'),
  ('50min_base_ride_2', 'b76pWjK68c'),
  ('25hr_endurance_ride_3', '8qFh5IlL0i'),
  ('75min_base_ride_3', 'pp9wyINlTN'),
  ('60min_mixed_workout_5', 'KD_xwHo-j3'),
  ('40min_sweet_spot_2', 'dZ0O24pU07'),
  ('40min_base_ride', '2Sahgzcl2-'),
  ('65min_base_ride_3', 'Gzg4q8FH3F'),
  ('16hr_endurance_ride', 'HNAk3ctpJ_'),
  ('20hr_endurance_ride_3', '7-bKEV4awA'),
  ('3x6min_threshold_intervals', '8JZasWcCs2'),
  ('50min_base_ride_3', 'PUYdHskJ3h'),
  ('2x8min_sweet_spot', '-5u3hfeznQ'),
  ('20min_tempo', 'SsVvir4nPm'),
  ('24hr_endurance_ride_3', 'qJP6zkNhpx'),
  ('3x6min_vo2_max_intervals', 'V9WansU36e'),
  ('50min_base_ride_4', 'DJCyJ5Ap0-'),
  ('3x2min_vo2_max_intervals', '3dKbRzxFuT'),
  ('15min_tempo', '1seWiwilUL'),
  ('24hr_endurance_ride_4', 'ItjH6SSdfq'),
  ('25min_tempo', 'E9i7Dh_TUT'),
  ('2x3min_vo2_max_intervals_3', 'WKGmf1vM6A'),
  ('2x1min_sweet_spot', 'vz76Ultxl0'),
  ('20min_tempo_2', '33S4ZEFILK'),
  ('60min_base_ride_5', 'yIjk49Le0V'),
  ('90min_tempo', 't6mEjoBwFN'),
  ('2x15min_vo2_max_intervals_2', '6p-vXr8v1f'),
  ('120min_tempo', 'FgARwj_fr7');

-- Function to update library_workout_id in JSONB plan_data
CREATE OR REPLACE FUNCTION migrate_workout_ids_in_plan_data(plan_data JSONB)
RETURNS JSONB AS $$
DECLARE
  updated_plan_data JSONB;
  weekly_plan JSONB;
  updated_weekly_plan JSONB;
  week_item JSONB;
  updated_week_item JSONB;
  workouts JSONB;
  updated_workouts JSONB;
  workout JSONB;
  updated_workout JSONB;
  old_workout_id TEXT;
  new_workout_id TEXT;
  i INT;
  j INT;
BEGIN
  -- Start with original plan_data
  updated_plan_data := plan_data;

  -- Get weekly_plan array
  weekly_plan := plan_data->'weekly_plan';

  IF weekly_plan IS NULL OR jsonb_array_length(weekly_plan) = 0 THEN
    RETURN plan_data;
  END IF;

  -- Build new weekly_plan array
  updated_weekly_plan := '[]'::JSONB;

  FOR i IN 0..jsonb_array_length(weekly_plan) - 1 LOOP
    week_item := weekly_plan->i;
    workouts := week_item->'workouts';

    IF workouts IS NOT NULL AND jsonb_array_length(workouts) > 0 THEN
      updated_workouts := '[]'::JSONB;

      FOR j IN 0..jsonb_array_length(workouts) - 1 LOOP
        workout := workouts->j;
        updated_workout := workout;

        -- Check if this workout has a library_workout_id
        old_workout_id := workout->>'library_workout_id';

        IF old_workout_id IS NOT NULL THEN
          -- Look up the new ID
          SELECT new_id INTO new_workout_id
          FROM workout_id_mapping
          WHERE old_id = old_workout_id;

          IF new_workout_id IS NOT NULL THEN
            -- Update the library_workout_id
            updated_workout := jsonb_set(updated_workout, '{library_workout_id}', to_jsonb(new_workout_id));
          END IF;
        END IF;

        updated_workouts := updated_workouts || updated_workout;
      END LOOP;

      updated_week_item := jsonb_set(week_item, '{workouts}', updated_workouts);
    ELSE
      updated_week_item := week_item;
    END IF;

    updated_weekly_plan := updated_weekly_plan || updated_week_item;
  END LOOP;

  -- Update plan_data with new weekly_plan
  updated_plan_data := jsonb_set(updated_plan_data, '{weekly_plan}', updated_weekly_plan);

  RETURN updated_plan_data;
END;
$$ LANGUAGE plpgsql;

-- Migrate training_plans table
UPDATE training_plans
SET plan_data = migrate_workout_ids_in_plan_data(plan_data)
WHERE plan_data->'weekly_plan' IS NOT NULL;

-- Migrate plan_instances table
UPDATE plan_instances
SET plan_data = migrate_workout_ids_in_plan_data(plan_data)
WHERE plan_data->'weekly_plan' IS NOT NULL;

-- Clean up
DROP FUNCTION migrate_workout_ids_in_plan_data(JSONB);
DROP TABLE workout_id_mapping;

-- Add comment for documentation
COMMENT ON TABLE training_plans IS 'Training plan templates. workout library_workout_id uses NanoID format (10 chars) as of migration 20260106000001';
COMMENT ON TABLE plan_instances IS 'Scheduled plan instances. workout library_workout_id uses NanoID format (10 chars) as of migration 20260106000001';
