# Cycling AI Configuration
version: "1.0"

# Default provider to use
default_provider: "anthropic"

# Provider configurations
providers:
  anthropic:
    model: "claude-sonnet-4"
    max_tokens: 4096
    temperature: 0.7
    api_key_env: "ANTHROPIC_API_KEY"

  openai:
    model: "gpt-4-turbo"
    max_tokens: 4096
    temperature: 0.7
    api_key_env: "OPENAI_API_KEY"

  gemini:
    model: "gemini-pro"
    max_tokens: 4096
    temperature: 0.7
    api_key_env: "GEMINI_API_KEY"

  ollama:
    model: "llama3"
    max_tokens: 4096
    temperature: 0.7
    api_key_env: ""  # No API key needed for local

# Analysis defaults
analysis:
  period_months: 6
  use_cache: true

# Training plan defaults
training:
  total_weeks: 12

# Paths (optional, can be overridden by CLI)
paths:
  athlete_profile: ""  # Auto-detect from current directory
  activities_csv: ""
  fit_files_directory: ""

# Output preferences
output:
  format: "rich"  # "json", "markdown", "rich"
  verbose: false
  color: true
