"""Generate HTML performance analysis reports from JSON data."""
from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path
from typing import Dict, Any

from cycling_ai.models.performance_analysis import PerformanceAnalysis


def generate_performance_html_from_json(
    report_data: Dict[str, Any],
    output_path: Path | str
) -> None:
    """
    Generate HTML performance analysis report from report_data.json structure.

    This is the new template-based approach that reads complete report_data.json
    and generates HTML without LLM involvement.

    Args:
        report_data: Complete report data dictionary (from report_data.json)
        output_path: Path where HTML file should be written
    """
    import logging
    logger = logging.getLogger(__name__)

    logger.debug(f"[PERF HTML] Starting generation, output_path={output_path}")

    # Extract first athlete from report data
    athletes = report_data.get("athletes", [])
    logger.debug(f"[PERF HTML] Found {len(athletes)} athletes")
    if not athletes:
        raise ValueError("No athletes found in report_data")

    athlete = athletes[0]  # For now, support single athlete
    performance_analysis = athlete.get("performance_analysis")
    logger.debug(f"[PERF HTML] Performance analysis type: {type(performance_analysis)}")

    if not performance_analysis:
        raise ValueError("No performance analysis data found in report_data")

    # If performance_analysis is a JSON string, parse it first
    if isinstance(performance_analysis, str):
        logger.debug("[PERF HTML] Parsing performance_analysis from JSON string")
        import json
        performance_analysis = json.loads(performance_analysis)

    # Now validate it's a dict
    if not isinstance(performance_analysis, dict):
        raise ValueError(
            f"performance_analysis must be a dict after parsing, got {type(performance_analysis).__name__}"
        )

    logger.debug("[PERF HTML] Validating with Pydantic model")
    # Convert to PerformanceAnalysis model using Pydantic v2
    analysis = PerformanceAnalysis.model_validate(performance_analysis)

    logger.debug("[PERF HTML] Calling generate_performance_html")
    # Use existing HTML generation
    generate_performance_html(analysis, output_path)
    logger.debug("[PERF HTML] HTML generation completed")


def generate_performance_html(analysis: PerformanceAnalysis, output_path: Path | str) -> None:
    """
    Generate HTML performance analysis report from structured JSON data.

    Args:
        analysis: Validated performance analysis data
        output_path: Path where HTML file should be written
    """
    import logging
    logger = logging.getLogger(__name__)

    logger.debug("[PERF HTML] Building HTML content")
    html_content = _build_html(analysis)
    logger.debug(f"[PERF HTML] HTML content built, length={len(html_content)} chars")

    output_file = Path(output_path)
    logger.debug(f"[PERF HTML] Creating parent directory for {output_file}")
    output_file.parent.mkdir(parents=True, exist_ok=True)

    logger.debug(f"[PERF HTML] Writing HTML to {output_file}")
    with open(output_file, "w", encoding="utf-8") as f:
        f.write(html_content)
    logger.debug("[PERF HTML] HTML file written successfully")


def _build_html(analysis: PerformanceAnalysis) -> str:
    """Build complete HTML document from analysis data."""
    css = _get_css()
    body = _build_body(analysis)

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Performance Analysis Report - {analysis.athlete_profile.name}</title>
    <style>
{css}
    </style>
</head>
<body>
    <div class="report-container">
        <header class="report-header">
            <h1>Performance Analysis Report</h1>
            <p class="report-subtitle">{analysis.athlete_profile.name} • {analysis.analysis_period_months} Month Analysis Period</p>
        </header>

        <main class="report-content">
{body}
        </main>

        <footer class="report-footer">
            <p>Generated by Cycling AI Analysis • {datetime.now().strftime('%B %d, %Y')}</p>
        </footer>
    </div>
</body>
</html>"""


def _build_body(analysis: PerformanceAnalysis) -> str:
    """Build the main content body."""
    sections = []

    # Athlete Profile
    sections.append(_build_athlete_profile(analysis.athlete_profile))

    # Performance Comparison
    if analysis.performance_comparison:
        sections.append(_build_performance_comparison(analysis.performance_comparison))

    # Time in Zones
    if analysis.time_in_zones:
        sections.append(_build_time_in_zones(analysis.time_in_zones))

    # Key Trends
    if analysis.key_trends:
        sections.append(_build_key_trends(analysis.key_trends))

    # Insights
    if analysis.insights:
        sections.append(_build_insights(analysis.insights))

    # Recommendations
    sections.append(_build_recommendations(analysis.recommendations))

    return "\n".join(sections)


def _build_athlete_profile(profile) -> str:
    """Build athlete profile section."""
    html = '<div class="section-athlete_profile" id="athlete_profile">\n'
    html += '<h2>Athlete Profile</h2>\n'
    html += '<div class="profile-grid">\n'

    # Add profile items
    items = [
        ("Name", profile.name),
        ("Current FTP", f"{profile.current_ftp}W"),
        ("Weight", f"{profile.weight}kg"),
        ("W/kg", f"{profile.w_kg:.2f}"),
    ]

    if profile.age:
        items.append(("Age", str(profile.age)))

    if profile.experience_level:
        items.append(("Experience Level", profile.experience_level))

    for label, value in items:
        html += f'  <div class="profile-item">\n'
        html += f'    <div class="profile-label">{label}</div>\n'
        html += f'    <div class="profile-value">{value}</div>\n'
        html += f'  </div>\n'

    html += '</div>\n'
    html += '</div>\n'
    return html


def _build_performance_comparison(metrics) -> str:
    """Build performance comparison table."""
    html = '<div class="section-performance_comparison" id="performance_comparison">\n'
    html += '<h2>Performance Comparison</h2>\n'
    html += '<table class="comparison-table">\n'
    html += '  <thead>\n'
    html += '    <tr>\n'
    html += '      <th>Metric</th>\n'
    html += '      <th>Previous Period</th>\n'
    html += '      <th>Current Period</th>\n'
    html += '      <th>Change</th>\n'
    html += '    </tr>\n'
    html += '  </thead>\n'
    html += '  <tbody>\n'

    for metric in metrics:
        trend_class = f"trend-{metric.trend}"
        arrow = "↑" if metric.trend == "up" else "↓" if metric.trend == "down" else "→"

        html += '    <tr>\n'
        html += f'      <td class="metric-name">{metric.metric}</td>\n'
        html += f'      <td>{metric.previous}</td>\n'
        html += f'      <td>{metric.current}</td>\n'
        html += f'      <td class="{trend_class}">{arrow} {metric.change}</td>\n'
        html += '    </tr>\n'

    html += '  </tbody>\n'
    html += '</table>\n'
    html += '</div>\n'
    return html


def _build_time_in_zones(zones) -> str:
    """Build time in zones section."""
    html = '<div class="section-time_in_zones" id="time_in_zones">\n'
    html += '<h2>Time In Zones</h2>\n'
    html += '<div class="zones-container">\n'

    for zone in zones:
        html += f'  <div class="zone-item">\n'
        html += f'    <div class="zone-header">\n'
        html += f'      <span class="zone-badge">Zone {zone.zone}</span>\n'
        html += f'      <span class="zone-name">{zone.name}</span>\n'
        html += f'    </div>\n'
        html += f'    <div class="zone-stats">\n'
        html += f'      <span class="zone-percentage">{zone.percentage:.1f}%</span>\n'
        html += f'      <span class="zone-hours">{zone.hours:.1f}h</span>\n'
        html += f'    </div>\n'
        html += f'    <div class="zone-bar">\n'
        html += f'      <div class="zone-bar-fill" style="width: {zone.percentage}%"></div>\n'
        html += f'    </div>\n'
        html += f'  </div>\n'

    html += '</div>\n'
    html += '</div>\n'
    return html


def _build_key_trends(trends) -> str:
    """Build key trends section."""
    html = '<div class="section-key_trends" id="key_trends">\n'
    html += '<h2>Key Trends</h2>\n'
    html += '<ol class="trends-list">\n'

    for trend in trends:
        html += '  <li>\n'
        html += f'    <strong>{trend.title}</strong>: {trend.description}\n'
        html += '  </li>\n'

    html += '</ol>\n'
    html += '</div>\n'
    return html


def _build_insights(insights) -> str:
    """Build insights section."""
    html = '<div class="section-insights" id="insights">\n'
    html += '<h2>Insights</h2>\n'
    html += '<ol class="insights-list">\n'

    for insight in insights:
        html += '  <li>\n'
        html += f'    <strong>{insight.title}</strong>: {insight.description}\n'
        html += '  </li>\n'

    html += '</ol>\n'
    html += '</div>\n'
    return html


def _build_recommendations(recs) -> str:
    """Build recommendations section."""
    html = '<div class="section-recommendations" id="recommendations">\n'
    html += '<h2>Recommendations</h2>\n'

    if recs.short_term:
        html += '<h3>Short-term Focus (Next 4 weeks)</h3>\n'
        html += '<ul class="recommendations-list">\n'
        for rec in recs.short_term:
            html += f'  <li>{rec.text}</li>\n'
        html += '</ul>\n'

    if recs.long_term:
        html += '<h3>Long-term Goals (3-6 months)</h3>\n'
        html += '<ul class="recommendations-list">\n'
        for rec in recs.long_term:
            html += f'  <li>{rec.text}</li>\n'
        html += '</ul>\n'

    if recs.recovery_nutrition:
        html += '<h3>Recovery and Nutrition</h3>\n'
        html += '<ul class="recommendations-list">\n'
        for rec in recs.recovery_nutrition:
            html += f'  <li>{rec.text}</li>\n'
        html += '</ul>\n'

    html += '</div>\n'
    return html


def _get_css() -> str:
    """Get the CSS for the HTML report."""
    return """        /* Custom Professional Palette - Cycling Inspired (matches training plan viewer) */
        :root {
            --primary-dark: #1a2332;
            --primary-mid: #2d3e50;
            --accent-orange: #ff6b35;
            --accent-teal: #004e89;
            --accent-yellow: #ffc857;
            --success-green: #06d6a0;
            --bg-light: #f8f9fa;
            --bg-card: #ffffff;
            --text-primary: #1a2332;
            --text-secondary: #5a6c7d;
            --text-light: #8492a6;
            --border-light: #e1e8ed;
            --shadow-sm: 0 2px 8px rgba(26, 35, 50, 0.08);
            --shadow-md: 0 4px 16px rgba(26, 35, 50, 0.12);
            --shadow-lg: 0 8px 32px rgba(26, 35, 50, 0.16);
        }

        /* Base styles */
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body {
            font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, sans-serif;
            line-height: 1.6;
            color: var(--text-primary);
            background: linear-gradient(135deg, #f8f9fa 0%, #e9ecef 100%);
            min-height: 100vh;
            padding: 20px;
        }

        .report-container {
            max-width: 1200px;
            margin: 0 auto;
            background: white;
            padding: 0;
            border-radius: 16px;
            box-shadow: var(--shadow-lg);
            overflow: hidden;
        }

        /* Modern Header with Gradient */
        .report-header {
            background: linear-gradient(135deg, var(--primary-dark) 0%, var(--primary-mid) 100%);
            color: white;
            padding: 2.5rem 2rem;
            position: sticky;
            top: 0;
            z-index: 1000;
            box-shadow: var(--shadow-lg);
        }

        .report-header h1 {
            font-size: 2.5em;
            margin-bottom: 0.75rem;
            font-weight: 700;
            letter-spacing: -0.5px;
        }

        .report-subtitle {
            font-size: 1.1em;
            opacity: 0.95;
            font-weight: 400;
            margin-top: 0.5rem;
        }

        /* Content area */
        .report-content {
            padding: 2.5rem;
        }

        /* Footer */
        .report-footer {
            background: var(--bg-light);
            padding: 1.5rem 2rem;
            text-align: center;
            color: var(--text-secondary);
            font-size: 0.9em;
            border-top: 1px solid var(--border-light);
        }

        /* Section styles */
        [class^="section-"] {
            margin-bottom: 3rem;
            padding-bottom: 2rem;
            border-bottom: 2px solid var(--border-light);
        }

        [class^="section-"]:last-child {
            border-bottom: none;
        }

        [class^="section-"] h2 {
            color: var(--primary-dark);
            font-size: 1.75em;
            font-weight: 700;
            margin-bottom: 1.5rem;
            padding-bottom: 0.75rem;
            border-bottom: 3px solid var(--accent-orange);
            display: inline-block;
        }

        [class^="section-"] h3 {
            color: var(--primary-mid);
            font-size: 1.25em;
            font-weight: 600;
            margin: 1.5rem 0 1rem 0;
        }

        /* Athlete Profile */
        .profile-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
            gap: 1.25rem;
            margin-top: 1.5rem;
        }

        .profile-item {
            background: linear-gradient(135deg, #f8f9fa 0%, #e9ecef 100%);
            padding: 1.5rem;
            border-radius: 12px;
            border-left: 4px solid var(--accent-orange);
            transition: all 0.3s ease;
        }

        .profile-item:hover {
            transform: translateY(-4px);
            box-shadow: var(--shadow-md);
            border-left-color: var(--accent-teal);
        }

        .profile-label {
            font-size: 0.85em;
            color: var(--text-secondary);
            text-transform: uppercase;
            letter-spacing: 0.5px;
            font-weight: 600;
            margin-bottom: 0.5rem;
        }

        .profile-value {
            font-size: 1.5em;
            color: var(--primary-dark);
            font-weight: 700;
        }

        /* Performance Comparison Table */
        .comparison-table {
            width: 100%;
            border-collapse: separate;
            border-spacing: 0;
            margin-top: 1.5rem;
            background: white;
            border-radius: 12px;
            overflow: hidden;
            box-shadow: var(--shadow-sm);
        }

        .comparison-table thead {
            background: linear-gradient(135deg, var(--primary-dark) 0%, var(--primary-mid) 100%);
            color: white;
        }

        .comparison-table th {
            padding: 1rem 1.25rem;
            text-align: left;
            font-weight: 600;
            font-size: 0.95em;
            text-transform: uppercase;
            letter-spacing: 0.5px;
        }

        .comparison-table td {
            padding: 1rem 1.25rem;
            border-bottom: 1px solid var(--border-light);
        }

        .comparison-table tbody tr:last-child td {
            border-bottom: none;
        }

        .comparison-table tbody tr:hover {
            background: var(--bg-light);
        }

        .metric-name {
            font-weight: 600;
            color: var(--primary-dark);
        }

        .trend-up {
            color: var(--success-green);
            font-weight: 600;
        }

        .trend-down {
            color: #ef476f;
            font-weight: 600;
        }

        .trend-neutral {
            color: var(--text-secondary);
            font-weight: 600;
        }

        /* Zone Distribution */
        .zones-container {
            margin-top: 1.5rem;
        }

        .zone-item {
            background: white;
            padding: 1.25rem;
            border-radius: 12px;
            margin-bottom: 1rem;
            border: 1px solid var(--border-light);
            transition: all 0.3s ease;
        }

        .zone-item:hover {
            box-shadow: var(--shadow-md);
            transform: translateX(4px);
        }

        .zone-header {
            display: flex;
            align-items: center;
            gap: 1rem;
            margin-bottom: 0.75rem;
        }

        .zone-badge {
            background: linear-gradient(135deg, var(--accent-teal) 0%, #0066a8 100%);
            color: white;
            padding: 0.4rem 0.8rem;
            border-radius: 20px;
            font-size: 0.85em;
            font-weight: 600;
        }

        .zone-name {
            font-weight: 600;
            color: var(--primary-dark);
            font-size: 1.1em;
        }

        .zone-stats {
            display: flex;
            gap: 1.5rem;
            margin-bottom: 0.75rem;
            font-size: 0.95em;
        }

        .zone-percentage {
            color: var(--accent-orange);
            font-weight: 700;
            font-size: 1.2em;
        }

        .zone-hours {
            color: var(--text-secondary);
        }

        .zone-bar {
            width: 100%;
            height: 8px;
            background: var(--border-light);
            border-radius: 4px;
            overflow: hidden;
        }

        .zone-bar-fill {
            height: 100%;
            background: linear-gradient(90deg, var(--accent-orange) 0%, var(--accent-yellow) 100%);
            transition: width 0.6s ease;
        }

        /* Lists */
        .trends-list,
        .insights-list {
            counter-reset: item;
            list-style: none;
            padding-left: 0;
        }

        .trends-list li,
        .insights-list li {
            position: relative;
            padding: 1.25rem 1.5rem 1.25rem 4rem;
            margin-bottom: 1rem;
            background: white;
            border-radius: 12px;
            border-left: 4px solid var(--accent-teal);
            box-shadow: var(--shadow-sm);
            counter-increment: item;
            transition: all 0.3s ease;
        }

        .trends-list li:hover,
        .insights-list li:hover {
            transform: translateX(4px);
            box-shadow: var(--shadow-md);
        }

        .trends-list li::before,
        .insights-list li::before {
            content: counter(item);
            position: absolute;
            left: 1rem;
            top: 1.25rem;
            background: linear-gradient(135deg, var(--accent-orange) 0%, #ff8c5a 100%);
            color: white;
            width: 36px;
            height: 36px;
            border-radius: 50%;
            display: flex;
            align-items: center;
            justify-content: center;
            font-weight: 700;
            font-size: 1.1em;
            box-shadow: rgba(255, 107, 53, 0.3) 0px 4px 12px;
        }

        .recommendations-list {
            list-style: none;
            padding-left: 0;
        }

        .recommendations-list li {
            position: relative;
            padding: 1rem 1.25rem 1rem 3rem;
            margin-bottom: 0.75rem;
            background: var(--bg-light);
            border-radius: 8px;
            transition: all 0.2s ease;
        }

        .recommendations-list li:hover {
            background: white;
            box-shadow: var(--shadow-sm);
            transform: translateX(4px);
        }

        .recommendations-list li::before {
            content: "✓";
            position: absolute;
            left: 1rem;
            color: var(--success-green);
            font-weight: 700;
            font-size: 1.2em;
        }

        /* Responsive Design */
        @media (max-width: 768px) {
            body {
                padding: 10px;
            }

            .report-header {
                padding: 1.5rem 1rem;
            }

            .report-header h1 {
                font-size: 1.75em;
            }

            .report-content {
                padding: 1.5rem 1rem;
            }

            .profile-grid {
                grid-template-columns: 1fr;
            }

            .comparison-table {
                font-size: 0.9em;
            }

            .comparison-table th,
            .comparison-table td {
                padding: 0.75rem 0.5rem;
            }
        }

        /* Print Styles */
        @media print {
            body {
                background: white;
                padding: 0;
            }

            .report-container {
                box-shadow: none;
                border-radius: 0;
            }

            .report-header {
                position: relative;
            }

            [class^="section-"] {
                page-break-inside: avoid;
            }

            .profile-item:hover,
            .zone-item:hover,
            .trends-list li:hover,
            .insights-list li:hover,
            .recommendations-list li:hover {
                transform: none;
                box-shadow: none;
            }
        }
    """
