"""
Training plan generation module.

This module provides functionality to generate progressive, periodized training plans
based on an athlete's current fitness, goals, and availability. Creates structured
week-by-week plans with Foundation, Build, Recovery, and Peak phases.

Outputs structured JSON for integration with report generators.
"""

import json
from typing import Any

from .utils import convert_to_json_serializable
from .workout_builder import (
    build_endurance_workout,
    build_sweetspot_workout,
    build_tempo_workout,
    build_threshold_workout,
    build_vo2max_workout,
)


def generate_training_plan(
    current_ftp: float,
    available_days_per_week: int,
    target_ftp: float = None,
    total_weeks: int = 12,
    athlete_age: int = None,
    athlete_profile: Any = None
) -> str:
    """
    Generate a progressive training plan based on athlete's availability and goals.

    Creates a periodized plan with foundation, build, recovery, and peak phases.
    Automatically adjusts intensity and volume based on available training days.

    Args:
        current_ftp: Current Functional Threshold Power in watts
        available_days_per_week: Number of days available for training (3-7)
        target_ftp: Target FTP (optional, defaults to +6% of current)
        total_weeks: Duration of plan in weeks (4-24, default: 12)
        athlete_age: Athlete's age (for recovery adjustments, default: 40)

    Returns:
        Formatted training plan as markdown string
    """
    # Set defaults
    if target_ftp is None:
        target_ftp = int(current_ftp * 1.06)

    # Validate inputs
    if available_days_per_week < 3 or available_days_per_week > 7:
        return "❌ Error: Available days must be between 3 and 7 days per week."

    if total_weeks < 4 or total_weeks > 24:
        return "❌ Error: Plan duration must be between 4 and 24 weeks."

    # Calculate zones
    z1_max = int(current_ftp * 0.6)
    z2_min, z2_max = int(current_ftp * 0.6), int(current_ftp * 0.8)
    z3_min, z3_max = int(current_ftp * 0.8), int(current_ftp * 0.9)
    z4_min, z4_max = int(current_ftp * 0.9), int(current_ftp * 1.1)
    z5_min = int(current_ftp * 1.1)
    ss_min, ss_max = int(current_ftp * 0.88), int(current_ftp * 0.93)

    # Build response
    response_text = f"# 📋 {total_weeks}-Week Progressive Training Plan\n\n"
    response_text += "## 🎯 Goals & Parameters\n"
    response_text += f"- **Current FTP:** {current_ftp}W\n"
    response_text += f"- **Target FTP:** {target_ftp}W (+{((target_ftp/current_ftp - 1) * 100):.1f}%)\n"
    response_text += f"- **Training Days:** {available_days_per_week} days/week\n"
    response_text += f"- **Duration:** {total_weeks} weeks\n"
    response_text += f"- **Age:** {athlete_age} years\n\n"

    response_text += "## ⚡ Your Power Zones\n"
    response_text += f"- **Z1 (Active Recovery):** 0-{z1_max}W\n"
    response_text += f"- **Z2 (Endurance):** {z2_min}-{z2_max}W\n"
    response_text += f"- **Z3 (Tempo):** {z3_min}-{z3_max}W\n"
    response_text += f"- **Z4 (Threshold):** {z4_min}-{z4_max}W\n"
    response_text += f"- **Z5 (VO2 Max):** >{z5_min}W\n"
    response_text += f"- **Sweet Spot:** {ss_min}-{ss_max}W\n\n"

    # Recovery and monitoring guidance will be generated by LLM based on athlete profile
    response_text += "---\n\n"

    # Generate week-by-week plan
    for week in range(1, total_weeks + 1):
        # Determine phase
        recovery_week_positions = [total_weeks // 3, (2 * total_weeks) // 3]
        is_recovery = week in recovery_week_positions

        if week <= total_weeks // 3:
            phase = "Foundation"
            phase_emoji = "🏗️"
        elif week <= (2 * total_weeks) // 3:
            phase = "Build"
            phase_emoji = "💪"
        else:
            phase = "Peak"
            phase_emoji = "🏔️"

        if is_recovery:
            phase = "Recovery"
            phase_emoji = "😌"

        response_text += f"## Week {week}: {phase_emoji} {phase} Phase\n\n"

        # Generate daily workouts based on available days
        if is_recovery:
            # Recovery week - reduce volume and intensity
            if available_days_per_week >= 5:
                workouts = [
                    ("Monday", "Rest", None),
                    ("Tuesday", "Easy Endurance", f"60 min Z2 ({z2_min}-{z2_max}W), conversational pace"),
                    ("Wednesday", "Rest", None),
                    ("Thursday", "Sweet Spot", f"15 min warm-up + 2x10 @ {ss_min}-{ss_max}W, 5 min recovery + 10 min cool-down"),
                    ("Friday", "Rest", None),
                    ("Saturday", "Medium Endurance", "2.5 hrs Z2, include 3x5 min tempo"),
                    ("Sunday", "Rest", None),
                ]
            else:
                workouts = [
                    ("Monday", "Rest", None),
                    ("Wednesday", "Easy Endurance", f"60 min Z2 ({z2_min}-{z2_max}W)"),
                    ("Friday", "Rest", None),
                    ("Saturday", "Medium Endurance", "2 hrs Z2, easy pace"),
                ]

        elif phase == "Foundation":
            # Build base and introduce threshold
            threshold_work = "2x15" if week <= 2 else "2x20"

            if available_days_per_week >= 5:
                workouts = [
                    ("Monday", "Rest", None),
                    ("Tuesday", "Threshold", f"10 min warm-up + {threshold_work} @ {z4_min}-{int(current_ftp * 0.95)}W, 5 min recovery + cool-down"),
                    ("Wednesday", "Endurance", f"60 min Z2 ({z2_min}-{z2_max}W)"),
                    ("Thursday", "Tempo", f"10 min warm-up + 3x15 @ {z3_min}-{z3_max}W, 5 min recovery + cool-down"),
                    ("Friday", "Rest", None),
                    ("Saturday", "Long Endurance", f"{3.0 + week * 0.2:.1f} hrs Z2, include 3x5 min tempo bursts"),
                    ("Sunday", "Recovery Ride", "60 min Z1-Z2, very easy"),
                ]
            elif available_days_per_week == 4:
                workouts = [
                    ("Tuesday", "Threshold", f"{threshold_work} @ {z4_min}-{int(current_ftp * 0.95)}W"),
                    ("Thursday", "Tempo", f"3x15 @ {z3_min}-{z3_max}W"),
                    ("Saturday", "Long Endurance", f"{3.0 + week * 0.2:.1f} hrs Z2"),
                    ("Sunday", "Recovery", "60 min easy"),
                ]
            else:  # 3 days
                workouts = [
                    ("Tuesday", "Threshold", f"{threshold_work} @ {z4_min}-{int(current_ftp * 0.95)}W"),
                    ("Friday", "Tempo", f"3x15 @ {z3_min}-{z3_max}W"),
                    ("Sunday", "Long Endurance", f"{3.0 + week * 0.3:.1f} hrs Z2"),
                ]

        elif phase == "Build":
            # Increase intensity with VO2 max work
            if available_days_per_week >= 5:
                workouts = [
                    ("Monday", "Rest", None),
                    ("Tuesday", "Threshold", f"10 min warm-up + 2x20 @ {z4_min}-{int(current_ftp * 0.95)}W + cool-down"),
                    ("Wednesday", "Endurance + Tempo", f"75 min, mostly Z2 with 2x10 @ {z3_min}-{z3_max}W"),
                    ("Thursday", "VO2 Max", f"15 min warm-up + 5x5 @ {z5_min}-{int(current_ftp * 1.1)}W, 5 min recovery + cool-down"),
                    ("Friday", "Rest", None),
                    ("Saturday", "Long Endurance", f"{3.5 + (week - 5) * 0.2:.1f} hrs Z2 + 3x10 tempo or 3x5 threshold"),
                    ("Sunday", "Sweet Spot", f"15 min warm-up + 3x15 @ {ss_min}-{ss_max}W + cool-down"),
                ]
            elif available_days_per_week == 4:
                workouts = [
                    ("Tuesday", "Threshold", f"2x20 @ {z4_min}-{int(current_ftp * 0.95)}W"),
                    ("Thursday", "VO2 Max", f"5x5 @ {z5_min}-{int(current_ftp * 1.1)}W"),
                    ("Saturday", "Long Endurance", f"{3.5:.1f} hrs with intensity"),
                    ("Sunday", "Sweet Spot", f"3x15 @ {ss_min}-{ss_max}W"),
                ]
            else:
                workouts = [
                    ("Tuesday", "Threshold", f"2x20 @ {z4_min}-{int(current_ftp * 0.95)}W"),
                    ("Friday", "VO2 Max", f"5x5 @ {z5_min}-{int(current_ftp * 1.1)}W"),
                    ("Sunday", "Long Endurance", f"{4:.1f} hrs with efforts"),
                ]

        else:  # Peak phase
            if available_days_per_week >= 5:
                workouts = [
                    ("Monday", "Rest", None),
                    ("Tuesday", "Threshold", f"10 min warm-up + 2x20 @ {int(current_ftp * 0.95)}-{current_ftp}W + cool-down"),
                    ("Wednesday", "Endurance + Bursts", "90 min Z2 with 5x3 min @ threshold"),
                    ("Thursday", "High Intensity VO2", f"15 min warm-up + 6x5 @ {int(current_ftp * 1.06)}-{int(current_ftp * 1.1)}W, 4 min recovery + cool-down"),
                    ("Friday", "Rest", "Prepare for weekend"),
                    ("Saturday", "Race Simulation", "2.5 hrs with race-like efforts: 3x15 @ threshold"),
                    ("Sunday", "Active Recovery", "90 min Z1-Z2, very easy"),
                ]
            elif available_days_per_week == 4:
                workouts = [
                    ("Tuesday", "Threshold", f"2x20 @ {int(current_ftp * 0.95)}-{current_ftp}W"),
                    ("Thursday", "VO2 Max", f"6x5 @ {int(current_ftp * 1.06)}-{int(current_ftp * 1.1)}W"),
                    ("Saturday", "Race Simulation", "2.5 hrs with race efforts"),
                    ("Sunday", "Recovery", "90 min easy"),
                ]
            else:
                workouts = [
                    ("Tuesday", "Threshold", f"2x20 @ {int(current_ftp * 0.95)}-{current_ftp}W"),
                    ("Friday", "VO2 Max", f"6x5 @ {int(current_ftp * 1.06)}-{int(current_ftp * 1.1)}W"),
                    ("Sunday", "Long with Efforts", "3 hrs with intervals"),
                ]

        # Format workouts
        for day, workout_type, details in workouts:
            if details:
                response_text += f"**{day}: {workout_type}**\n"
                response_text += f"- {details}\n\n"
            elif workout_type == "Rest":
                response_text += f"**{day}: Rest**\n\n"

        response_text += "---\n\n"

    # Note: Weekly monitoring, red flags, and plan summary should be generated by LLM
    # based on athlete profile, goals, and plan structure for personalized guidance
    response_text += "\n"

    # Generate structured weekly workouts
    weekly_workouts = _generate_weekly_workouts(
        total_weeks=total_weeks,
        available_days_per_week=available_days_per_week,
        current_ftp=int(current_ftp),
        athlete_age=athlete_age
    )

    # Build athlete profile data for LLM context
    athlete_profile_data = {
        'age': athlete_age,
        'ftp': float(current_ftp)
    }

    # Add extended profile data if available
    if athlete_profile:
        athlete_profile_data.update({
            'name': athlete_profile.name,
            'gender': athlete_profile.gender,
            'weight_kg': athlete_profile.weight_kg,
            'power_to_weight': float(current_ftp / athlete_profile.weight_kg) if athlete_profile.weight_kg else None,
            'max_hr': athlete_profile.max_hr,
            'training_availability': athlete_profile.training_availability,
            'goals': athlete_profile.goals,
            'current_training_status': athlete_profile.current_training_status,
            'available_training_days': athlete_profile.get_training_days(),
            'weekly_training_hours': athlete_profile.get_weekly_training_hours()
        })

    # Add context for LLM to generate personalized recommendations
    llm_context = {
        'plan_structure': {
            'total_weeks': total_weeks,
            'available_days_per_week': available_days_per_week,
            'phase_distribution': {
                'foundation_weeks': total_weeks // 3,
                'build_weeks': total_weeks // 3,
                'peak_weeks': total_weeks - (2 * (total_weeks // 3))
            },
            'recovery_weeks': [total_weeks // 3, (2 * total_weeks) // 3]
        },
        'ftp_progression': {
            'current': float(current_ftp),
            'target': float(target_ftp),
            'gain_watts': float(target_ftp - current_ftp),
            'gain_percent': float((target_ftp/current_ftp - 1) * 100)
        },
        'personalization_needed': [
            'recovery_strategy',
            'monitoring_priorities',
            'red_flags_specific_to_athlete',
            'plan_summary_with_rationale',
            'goal_alignment_assessment',
            'risk_factors',
            'success_probability'
        ]
    }

    # Return structured JSON with both data and formatted plan
    response_data = {
        'athlete_profile': athlete_profile_data,
        'llm_context': llm_context,
        'current_ftp': float(current_ftp),
        'target_ftp': float(target_ftp),
        'ftp_gain': float(target_ftp - current_ftp),
        'ftp_gain_percent': float((target_ftp/current_ftp - 1) * 100),
        'available_days_per_week': available_days_per_week,
        'total_weeks': total_weeks,
        'power_zones': {
            'z1': {'name': 'Active Recovery', 'min': 0, 'max': z1_max},
            'z2': {'name': 'Endurance', 'min': z2_min, 'max': z2_max},
            'z3': {'name': 'Tempo', 'min': z3_min, 'max': z3_max},
            'z4': {'name': 'Threshold', 'min': z4_min, 'max': z4_max},
            'z5': {'name': 'VO2 Max', 'min': z5_min, 'max': None},
            'sweet_spot': {'name': 'Sweet Spot', 'min': ss_min, 'max': ss_max}
        },
        'plan_text': response_text,  # Include formatted plan for display
        'weekly_workouts': weekly_workouts  # Structured workout data with SVGs
    }

    # Convert all numpy/pandas types to JSON-serializable types
    response_data = convert_to_json_serializable(response_data)

    return json.dumps(response_data, indent=2)


def _generate_weekly_workouts(total_weeks: int, available_days_per_week: int,
                               current_ftp: int, athlete_age: int = None) -> list:
    """
    Generate structured weekly workouts with detailed segments and SVG visualizations.

    Args:
        total_weeks: Number of weeks in the plan
        available_days_per_week: Training days per week
        current_ftp: Athlete's FTP
        athlete_age: Athlete's age

    Returns:
        List of weekly workout structures with SVG visualizations
    """
    weekly_plan = []

    for week in range(1, total_weeks + 1):
        # Determine phase
        recovery_week_positions = [total_weeks // 3, (2 * total_weeks) // 3]
        is_recovery = week in recovery_week_positions

        if week <= total_weeks // 3:
            phase = "Foundation"
        elif week <= (2 * total_weeks) // 3:
            phase = "Build"
        else:
            phase = "Peak"

        if is_recovery:
            phase = "Recovery"

        # Generate workouts for this week
        week_workouts = {}

        if is_recovery:
            # Recovery week
            if available_days_per_week >= 5:
                week_workouts['Tuesday'] = build_endurance_workout(current_ftp, 60)
                week_workouts['Thursday'] = build_sweetspot_workout(current_ftp, "2x10")
                week_workouts['Saturday'] = build_endurance_workout(current_ftp, 150)
            else:
                week_workouts['Wednesday'] = build_endurance_workout(current_ftp, 60)
                week_workouts['Saturday'] = build_endurance_workout(current_ftp, 120)

        elif phase == "Foundation":
            threshold_work = "2x15" if week <= 2 else "2x20"

            if available_days_per_week >= 5:
                week_workouts['Tuesday'] = build_threshold_workout(current_ftp, threshold_work, week)
                week_workouts['Wednesday'] = build_endurance_workout(current_ftp, 60)
                week_workouts['Thursday'] = build_tempo_workout(current_ftp, "3x15")
                week_workouts['Saturday'] = build_endurance_workout(current_ftp, int(180 + week * 12))
                week_workouts['Sunday'] = build_endurance_workout(current_ftp, 60)
            elif available_days_per_week == 4:
                week_workouts['Tuesday'] = build_threshold_workout(current_ftp, threshold_work, week)
                week_workouts['Thursday'] = build_tempo_workout(current_ftp, "3x15")
                week_workouts['Saturday'] = build_endurance_workout(current_ftp, int(180 + week * 12))
                week_workouts['Sunday'] = build_endurance_workout(current_ftp, 60)
            else:  # 3 days
                week_workouts['Tuesday'] = build_threshold_workout(current_ftp, threshold_work, week)
                week_workouts['Friday'] = build_tempo_workout(current_ftp, "3x15")
                week_workouts['Sunday'] = build_endurance_workout(current_ftp, int(180 + week * 18))

        elif phase == "Build":
            if available_days_per_week >= 5:
                week_workouts['Tuesday'] = build_threshold_workout(current_ftp, "2x20", week)
                week_workouts['Wednesday'] = build_endurance_workout(current_ftp, 75)
                week_workouts['Thursday'] = build_vo2max_workout(current_ftp, "5x5", week)
                week_workouts['Saturday'] = build_endurance_workout(current_ftp, int(210 + (week - 5) * 12))
                week_workouts['Sunday'] = build_sweetspot_workout(current_ftp, "3x15")
            elif available_days_per_week == 4:
                week_workouts['Tuesday'] = build_threshold_workout(current_ftp, "2x20", week)
                week_workouts['Thursday'] = build_vo2max_workout(current_ftp, "5x5", week)
                week_workouts['Saturday'] = build_endurance_workout(current_ftp, 210)
                week_workouts['Sunday'] = build_sweetspot_workout(current_ftp, "3x15")
            else:
                week_workouts['Tuesday'] = build_threshold_workout(current_ftp, "2x20", week)
                week_workouts['Friday'] = build_vo2max_workout(current_ftp, "5x5", week)
                week_workouts['Sunday'] = build_endurance_workout(current_ftp, 240)

        else:  # Peak phase
            if available_days_per_week >= 5:
                week_workouts['Tuesday'] = build_threshold_workout(current_ftp, "2x20", week)
                week_workouts['Wednesday'] = build_endurance_workout(current_ftp, 90)
                week_workouts['Thursday'] = build_vo2max_workout(current_ftp, "6x5", week)
                week_workouts['Saturday'] = build_endurance_workout(current_ftp, 150)
                week_workouts['Sunday'] = build_endurance_workout(current_ftp, 90)
            elif available_days_per_week == 4:
                week_workouts['Tuesday'] = build_threshold_workout(current_ftp, "2x20", week)
                week_workouts['Thursday'] = build_vo2max_workout(current_ftp, "6x5", week)
                week_workouts['Saturday'] = build_endurance_workout(current_ftp, 150)
                week_workouts['Sunday'] = build_endurance_workout(current_ftp, 90)
            else:
                week_workouts['Tuesday'] = build_threshold_workout(current_ftp, "2x20", week)
                week_workouts['Friday'] = build_vo2max_workout(current_ftp, "6x5", week)
                week_workouts['Sunday'] = build_endurance_workout(current_ftp, 180)

        # Convert workouts to dict format with SVG
        structured_workouts = {}
        for day, workout in week_workouts.items():
            workout_dict = workout.to_dict()
            workout_dict['svg'] = workout.generate_svg(width=600, height=200, ftp=current_ftp)
            structured_workouts[day] = workout_dict

        weekly_plan.append({
            'week': week,
            'phase': phase,
            'workouts': structured_workouts
        })

    return weekly_plan
