"""
ChromaVectorStore wrapper using LangChain.

This module provides a thin wrapper around LangChain's Chroma vectorstore
to support multi-collection management and our two-vectorstore design.

Examples:
    >>> from pathlib import Path
    >>> from cycling_ai.rag.embeddings import EmbeddingFactory
    >>> from cycling_ai.rag.vectorstore import ChromaVectorStore
    >>> from langchain_core.documents import Document
    >>>
    >>> # Create vectorstore
    >>> embeddings = EmbeddingFactory.create_local()
    >>> vectorstore = ChromaVectorStore(
    ...     persist_directory=Path("./my_vectorstore"),
    ...     embedding_function=embeddings
    ... )
    >>>
    >>> # Add documents
    >>> docs = [Document(page_content="Example text", metadata={"source": "test"})]
    >>> vectorstore.add_documents("my_collection", docs)
    >>>
    >>> # Search
    >>> results = vectorstore.similarity_search("my_collection", "example query", k=3)
"""

from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from langchain_core.documents import Document
    from langchain_core.embeddings import Embeddings


class ChromaVectorStore:
    """
    Wrapper around LangChain Chroma vectorstore.

    Manages multiple collections in a single Chroma instance.
    Supports our two-vectorstore design (project + user).

    Attributes:
        persist_directory: Directory for Chroma persistence
        embedding_function: LangChain Embeddings instance
    """

    def __init__(
        self,
        persist_directory: Path,
        embedding_function: Embeddings,
    ) -> None:
        """
        Initialize Chroma vectorstore wrapper.

        Args:
            persist_directory: Directory for Chroma persistence (created if needed)
            embedding_function: LangChain Embeddings instance

        Raises:
            OSError: If directory creation fails
        """
        self.persist_directory = persist_directory
        self.persist_directory.mkdir(parents=True, exist_ok=True)
        self.embedding_function = embedding_function

        # Collection cache: {collection_name: Chroma}
        self._collections: dict[str, Any] = {}

    def get_or_create_collection(
        self,
        collection_name: str,
    ) -> Any:  # Returns Chroma, but avoiding import for type checking
        """
        Get or create a Chroma collection.

        Uses LangChain's Chroma class to create/load collections.

        Args:
            collection_name: Name of collection

        Returns:
            LangChain Chroma instance

        Examples:
            >>> collection = vectorstore.get_or_create_collection("domain_knowledge")
        """
        if collection_name in self._collections:
            return self._collections[collection_name]

        # Import here to avoid circular dependency issues
        from langchain_community.vectorstores import Chroma

        # Create new collection using LangChain
        chroma = Chroma(
            collection_name=collection_name,
            embedding_function=self.embedding_function,
            persist_directory=str(self.persist_directory),
        )

        self._collections[collection_name] = chroma
        return chroma

    def add_documents(
        self,
        collection_name: str,
        documents: list[Document],
    ) -> list[str]:
        """
        Add documents to collection.

        Uses LangChain's Chroma.add_documents().

        Args:
            collection_name: Target collection
            documents: LangChain Document objects (page_content + metadata)

        Returns:
            List of document IDs (auto-generated by Chroma)

        Raises:
            ValueError: If documents list is empty

        Examples:
            >>> from langchain_core.documents import Document
            >>> docs = [
            ...     Document(
            ...         page_content="Polarized training is 80% low intensity...",
            ...         metadata={"category": "training_methodology"}
            ...     )
            ... ]
            >>> ids = vectorstore.add_documents("domain_knowledge", docs)
        """
        if not documents:
            raise ValueError("Cannot add empty documents list")

        collection = self.get_or_create_collection(collection_name)
        ids: list[str] = collection.add_documents(documents)
        return ids

    def similarity_search(
        self,
        collection_name: str,
        query: str,
        k: int = 5,
        filter: dict[str, Any] | None = None,
    ) -> list[Document]:
        """
        Search for similar documents.

        Uses LangChain's Chroma.similarity_search().

        Args:
            collection_name: Collection to search
            query: Search query (natural language)
            k: Number of results to return
            filter: Metadata filter (e.g., {"category": "performance"})

        Returns:
            List of LangChain Documents (most similar first)

        Examples:
            >>> results = vectorstore.similarity_search(
            ...     collection_name="domain_knowledge",
            ...     query="polarized training model",
            ...     k=3,
            ...     filter={"category": "training_methodology"}
            ... )
            >>> for doc in results:
            ...     print(doc.page_content)
            ...     print(doc.metadata)
        """
        collection = self.get_or_create_collection(collection_name)
        results: list[Document] = collection.similarity_search(
            query=query,
            k=k,
            filter=filter,
        )
        return results

    def similarity_search_with_score(
        self,
        collection_name: str,
        query: str,
        k: int = 5,
        filter: dict[str, Any] | None = None,
    ) -> list[tuple[Document, float]]:
        """
        Search with relevance scores.

        Uses LangChain's Chroma.similarity_search_with_score().

        Args:
            collection_name: Collection to search
            query: Search query
            k: Number of results
            filter: Metadata filter

        Returns:
            List of (Document, score) tuples
            Scores are cosine similarity (0-1, higher = more similar)

        Examples:
            >>> results = vectorstore.similarity_search_with_score(
            ...     collection_name="domain_knowledge",
            ...     query="FTP testing protocols",
            ...     k=5
            ... )
            >>> for doc, score in results:
            ...     print(f"Score: {score:.3f}")
            ...     print(f"Content: {doc.page_content[:100]}...")
        """
        collection = self.get_or_create_collection(collection_name)
        results: list[tuple[Document, float]] = collection.similarity_search_with_score(
            query=query,
            k=k,
            filter=filter,
        )
        return results

    def delete_collection(self, collection_name: str) -> None:
        """
        Delete a collection.

        Args:
            collection_name: Collection to delete

        Examples:
            >>> vectorstore.delete_collection("old_collection")
        """
        if collection_name in self._collections:
            collection = self._collections[collection_name]
            collection.delete_collection()
            del self._collections[collection_name]
